export const SERVER_AUTH_URL = process.env.REACT_APP_SERVER_AUTH_URL;
export const SERVER_LOGIN_URL = process.env.REACT_APP_SERVER_LOGIN_URL;
export const SERVER_LOGOUT_URL = process.env.REACT_APP_SERVER_LOGOUT_URL;
export const SERVER_TOKEN_URL = process.env.REACT_APP_SERVER_TOKEN_URL;
export const SERVER_GENERATE_PLAYLIST_URL = process.env.REACT_APP_SERVER_GENERATE_PLAYLIST_URL;

export const LOGIN_ENUM = {
    LOGGED_IN: 1,
    LOGGED_OUT: 2,
    LOGGING_IN: 3
};
